### ISSUE TITLE
ReservedConcurrentExecutions decreases UnreservedConcurrentExecution below minimum value

### ISSUE THREAD

**Issue by l0ris** [aws-samples/alarm-context-tool#2]
I am encountering an error when trying to deploy a stack using AWS SAM on us-wesr-2. The error message is as follows:

"ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID: 204aa629-d46e-47b8a3f695fea8fcf590)" (RequestToken: a35c5eb0-d1a2-cc17-adff-8a1fd84cd738, HandlerErrorCode: InvalidRequest)
The error is causing a rollback of the stack, with the following message:
ROLLBACK_IN_PROGRESS AWS::CloudFormation::Stack alarm-context-tool The following resource(s) failed to create: [AlarmContextFunction]. Rollback requested by user"

**To Reproduce**
1. Installed all the dependencies as per: "pip install -r ./dependencies_layer/requirements.txt &&
pip install aws_lambda_powertools 
2. Updated the template.yaml
3. Executed `sam build && sam deploy --guided`
Getting error as per screenshot attached 

**Expected behavior**
The deployment should be sucessful since my Concurrent Execution is set to 10 as per default
OS: Cloud9 AmazonLinux 2023 AMI
<img width="1427" alt="Screenshot 2024-06-04 at 16 55 26" src="https://github.com/aws-samples/alarm-context-tool/assets/7609376/b95df76c-4433-4430-ab94-72abf907a152">

**Comment by aelivingstone** [comment]
You have exceeded a Lambda limit in your account. [This Stack Overflow question](https://stackoverflow.com/questions/73988837/aws-specified-concurrentexecutions-for-function-decreases-accounts-unreservedc) explains it well. For a temporary fix to get yourself started, you can remove `ReservedConcurrentExecutions: 10` from template.yaml. I recommend that you request a limit increase though, otherwise you risk an alarm not triggering the Lambda function.

**Comment by l0ris** [comment]
I already requested increase of quota limit but getting the same error. It works by removing `ReservedConcurrentExecutions: 10`
